apiVersion: v1
kind: Service
metadata:
  name: postgresql-artifactory
  labels:
    app: postgresql-artifactory
spec:
  ports:
   - port: 5432
     protocol: TCP
  selector:
   app: postgresql-artifactory
