kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-artifactory-volume
  labels:
    type: local
    app: postgresql-artifactory
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/postgresql-artifactory"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-artifactory-claim
  labels:
    app: postgresql-artifactory
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
